### ISSUE TITLE
Performance Issues under Desktop

### ISSUE THREAD

**Issue by jlnrrg** [Milad-Akarie/skeletonizer#35]
I noticed that there seems to be a huge performance drop by using Skeletonizer on MacOS. 
(Also outlined by [this](https://www.reddit.com/r/FlutterDev/comments/18yfmvr/comment/kgbdpuw/) reddit comment)
It most likely might be a Flutter problem, thus I am just creating this issue to keep track of the state of things.

P.S. if you do not like tracking issues like this in your repository, feel free to close/ delete it.

**Comment by Milad-Akarie** [comment]
Hey @jlnrrg, have you compared the performance to other shimmer library? or is it animating over  a big canvas kinda thing?

**Comment by jlnrrg** [comment]
So I still don't know what caused the issue, but in my recent setup I saw no such performance issues:

These were the packages I assume could have had something to do with the issue.
In this version combination I saw no problem:

```yml
dependencies:
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0
  skeletonizer: ^1.4.2

dependency_overrides:
  accessibility_tools: ^2.2.1
  web: ^1.0.0

dev_dependencies:
  widgetbook_generator: ^3.8.0
```

Also I work under the most recent flutter version:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 12.7.5 21H1222 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
[!] Xcode - develop for iOS and macOS (Xcode 14.1)
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.1)
[✓] Connected device (2 available)
[✓] Network resources
```
